version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto de comunicación
      - "15672:15672" # Puerto de la interfaz web
    restart: always